# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Иван/Desktop/Музейное дело/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(399, 300)
        self.appyButton = QtWidgets.QPushButton(Settings)
        self.appyButton.setGeometry(QtCore.QRect(284, 252, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.appyButton.setFont(font)
        self.appyButton.setObjectName("appyButton")
        self.themeLabel = QtWidgets.QLabel(Settings)
        self.themeLabel.setGeometry(QtCore.QRect(20, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.themeLabel.setFont(font)
        self.themeLabel.setObjectName("themeLabel")
        self.themeComboBox = QtWidgets.QComboBox(Settings)
        self.themeComboBox.setGeometry(QtCore.QRect(20, 110, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.themeComboBox.setFont(font)
        self.themeComboBox.setObjectName("themeComboBox")
        self.Title = QtWidgets.QLabel(Settings)
        self.Title.setGeometry(QtCore.QRect(10, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.geometryComboBox = QtWidgets.QComboBox(Settings)
        self.geometryComboBox.setGeometry(QtCore.QRect(20, 190, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.geometryComboBox.setFont(font)
        self.geometryComboBox.setObjectName("geometryComboBox")
        self.geometryLabel = QtWidgets.QLabel(Settings)
        self.geometryLabel.setGeometry(QtCore.QRect(20, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.geometryLabel.setFont(font)
        self.geometryLabel.setObjectName("geometryLabel")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.appyButton.setText(_translate("Settings", "Применить"))
        self.themeLabel.setText(_translate("Settings", "Тема"))
        self.Title.setText(_translate("Settings", "Настройки"))
        self.geometryLabel.setText(_translate("Settings", "Геометрия окон"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
