# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Иван/Desktop/Музейное дело/addFormPartTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFormTwo(object):
    def setupUi(self, addFormTwo):
        addFormTwo.setObjectName("addFormTwo")
        addFormTwo.resize(502, 479)
        addFormTwo.setStyleSheet("")
        self.Title = QtWidgets.QLabel(addFormTwo)
        self.Title.setGeometry(QtCore.QRect(10, 15, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.labelGifter = QtWidgets.QLabel(addFormTwo)
        self.labelGifter.setGeometry(QtCore.QRect(20, 60, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelGifter.setFont(font)
        self.labelGifter.setObjectName("labelGifter")
        self.lineEditGifter = QtWidgets.QLineEdit(addFormTwo)
        self.lineEditGifter.setGeometry(QtCore.QRect(20, 90, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditGifter.setFont(font)
        self.lineEditGifter.setText("")
        self.lineEditGifter.setObjectName("lineEditGifter")
        self.labelDescription = QtWidgets.QLabel(addFormTwo)
        self.labelDescription.setGeometry(QtCore.QRect(20, 210, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDescription.setFont(font)
        self.labelDescription.setObjectName("labelDescription")
        self.textEditDescription = QtWidgets.QTextEdit(addFormTwo)
        self.textEditDescription.setGeometry(QtCore.QRect(20, 240, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEditDescription.setFont(font)
        self.textEditDescription.setObjectName("textEditDescription")
        self.labelPoint = QtWidgets.QLabel(addFormTwo)
        self.labelPoint.setGeometry(QtCore.QRect(20, 130, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPoint.setFont(font)
        self.labelPoint.setObjectName("labelPoint")
        self.lineEditPoint = QtWidgets.QLineEdit(addFormTwo)
        self.lineEditPoint.setGeometry(QtCore.QRect(20, 160, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditPoint.setFont(font)
        self.lineEditPoint.setText("")
        self.lineEditPoint.setObjectName("lineEditPoint")
        self.saveButton = QtWidgets.QPushButton(addFormTwo)
        self.saveButton.setGeometry(QtCore.QRect(360, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.backButton = QtWidgets.QPushButton(addFormTwo)
        self.backButton.setGeometry(QtCore.QRect(10, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")

        self.retranslateUi(addFormTwo)
        QtCore.QMetaObject.connectSlotsByName(addFormTwo)

    def retranslateUi(self, addFormTwo):
        _translate = QtCore.QCoreApplication.translate
        addFormTwo.setWindowTitle(_translate("addFormTwo", "Form"))
        self.Title.setText(_translate("addFormTwo", "Добавить экспонат"))
        self.labelGifter.setText(_translate("addFormTwo", "Даритель"))
        self.labelDescription.setText(_translate("addFormTwo", "Описание"))
        self.labelPoint.setText(_translate("addFormTwo", "Место хранения"))
        self.saveButton.setText(_translate("addFormTwo", "Добавить"))
        self.backButton.setText(_translate("addFormTwo", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addFormTwo = QtWidgets.QWidget()
    ui = Ui_addFormTwo()
    ui.setupUi(addFormTwo)
    addFormTwo.show()
    sys.exit(app.exec_())
