# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Иван/Desktop/Код/Resourses/Доп прога/OriginUI/singin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingIn(object):
    def setupUi(self, SingIn):
        SingIn.setObjectName("SingIn")
        SingIn.resize(624, 387)
        self.listWidget = QtWidgets.QListWidget(SingIn)
        self.listWidget.setGeometry(QtCore.QRect(20, 98, 591, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.Title = QtWidgets.QLabel(SingIn)
        self.Title.setGeometry(QtCore.QRect(10, 9, 611, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.editButton = QtWidgets.QPushButton(SingIn)
        self.editButton.setGeometry(QtCore.QRect(510, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editButton.setFont(font)
        self.editButton.setObjectName("editButton")
        self.exitButton = QtWidgets.QPushButton(SingIn)
        self.exitButton.setGeometry(QtCore.QRect(20, 338, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.addButton = QtWidgets.QPushButton(SingIn)
        self.addButton.setGeometry(QtCore.QRect(400, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.removeButton = QtWidgets.QPushButton(SingIn)
        self.removeButton.setGeometry(QtCore.QRect(280, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")

        self.retranslateUi(SingIn)
        QtCore.QMetaObject.connectSlotsByName(SingIn)

    def retranslateUi(self, SingIn):
        _translate = QtCore.QCoreApplication.translate
        SingIn.setWindowTitle(_translate("SingIn", "Form"))
        self.Title.setText(_translate("SingIn", "Вход в базу данных"))
        self.editButton.setText(_translate("SingIn", "Изменить"))
        self.exitButton.setText(_translate("SingIn", "Выйти"))
        self.addButton.setText(_translate("SingIn", "Добавить"))
        self.removeButton.setText(_translate("SingIn", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingIn = QtWidgets.QWidget()
    ui = Ui_SingIn()
    ui.setupUi(SingIn)
    SingIn.show()
    sys.exit(app.exec_())
