# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Иван/Desktop/Музейное дело/Subselection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subselection(object):
    def setupUi(self, Subselection):
        Subselection.setObjectName("Subselection")
        Subselection.resize(615, 369)
        Subselection.setStyleSheet("")
        self.Title = QtWidgets.QLabel(Subselection)
        self.Title.setGeometry(QtCore.QRect(10, 20, 601, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.labelSubselection = QtWidgets.QLabel(Subselection)
        self.labelSubselection.setGeometry(QtCore.QRect(20, 120, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSubselection.setFont(font)
        self.labelSubselection.setObjectName("labelSubselection")
        self.backButton = QtWidgets.QPushButton(Subselection)
        self.backButton.setGeometry(QtCore.QRect(10, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.pushButton_1 = QtWidgets.QPushButton(Subselection)
        self.pushButton_1.setEnabled(True)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 150, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Subselection)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 150, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Subselection)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 190, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Subselection)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 190, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Subselection)
        QtCore.QMetaObject.connectSlotsByName(Subselection)

    def retranslateUi(self, Subselection):
        _translate = QtCore.QCoreApplication.translate
        Subselection.setWindowTitle(_translate("Subselection", "Form"))
        self.Title.setText(_translate("Subselection", "..."))
        self.labelSubselection.setText(_translate("Subselection", "Выберите подраздел фонда музея"))
        self.backButton.setText(_translate("Subselection", "Назад"))
        self.pushButton_1.setText(_translate("Subselection", "..."))
        self.pushButton_2.setText(_translate("Subselection", "..."))
        self.pushButton_3.setText(_translate("Subselection", "..."))
        self.pushButton_4.setText(_translate("Subselection", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subselection = QtWidgets.QWidget()
    ui = Ui_Subselection()
    ui.setupUi(Subselection)
    Subselection.show()
    sys.exit(app.exec_())
